version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-jobs-backend
    restart: always
    depends_on:
      - database
    environment:
      - PORT=8086
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=leadsdb
      - FRONTEND_URL=http://localhost:8080
    ports:
      - "8086:8086"
    networks:
      - api-network

  database:
    image: postgres:14
    container_name: api-jobs-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=leadsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  postgres_data: